version: "3.7"
services:
  db:
    image: mariadb:10.5.8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  
  app:
    build: app
    restart: always
    volumes:
      - ./app/src:/src
    secrets:
      - db-password
    networks:
      - backend-network
      - frontend-network
  web:
    build: web
    restart: always
    volumes:
      - ./web/src:/usr/share/nginx/html/
    ports:
      - 80:80
    networks:
      - frontend-network
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  backend-network:
  frontend-network:
